#!/bin/sh 
# Copyright (c) Jul. 2017, Cheng-Yueh Liu (cyliustack@gmail.com)
# Potato is a pure GUI utility, like TensorBoard in TensorFlow.
if [ "$1" = "" ] ; then
    echo "Usage: potato /path/to/your/log/diretory"
    exit -1    
fi
logdir=$1
cp /opt/sofa/potatoboard/index.html ${logdir}
cp /opt/sofa/potatoboard/app.js ${logdir}
cp report.js ${logdir}
pushd ${logdir}; python -m SimpleHTTPServer; popd
