#!/bin/bash
# Copyright (c) Jul. 2017, Cheng-Yueh Liu (cyliustack@gmail.com)


C_NONE="\033[0m"
C_CYAN="\033[36m"
C_RED="\033[31m"
C_GREEN="\033[32m"
C_ORANGE="\033[33m"
C_BLUE="\033[34m"
C_PURPLE="\033[35m"
C_CYAN="\033[36m"
C_LIGHT_GRAY="\033[37m"

print_misc() {
    echo -e "${C_PURPLE} $1 ${C_NONE}"
}

print_info() {
    echo -e "${C_BLUE} $1 ${C_NONE}"
}

print_error() {
    echo -e "${C_RED} $1 ${C_NONE}"
}

print_warning() {
    echo -e "${C_ORANGE} $1 ${C_NONE}"
}



function collect_trace(){
    args=$*
    if [[ "$(cat /proc/sys/kernel/perf_event_paranoid)" == "-1" ]]; then 
        rm -f perf.data
        rm -f sofa.pcap
        #Communication Traces
        tcpdump -w sofa.pcap & 
        #Computation Traces
        date +%s > sofa_time.txt
        perf record -F 999 -a ${args} && pkill tcpdump
        perf script > perf.script
    else
        print_info "$(sysctl kernel.perf_event_paranoid)"
        print_error "PerfEvent is not avaiable, please try the command below:"
        print_error "sudo sysctl -w kernel.perf_event_paranoid=-1"
        exit -1       
    fi 
}

function generate_report(){
    print_info "FSA Configuration File: ${configFile}"
    print_info "script source = $(dirname $0)"
    $(dirname $0)/fsa ${configFile}
}

function print_help()
{
    echo "sofa [--config yourconfig.cfg] command"
}

function main()
{
    #args=$*
    configFile="default.cfg"
    print_info "SOFA: Function Swarm Analyzer"
    until [ $# -eq 0 ]
    do
        case "$1" in
            "--help" )
                print_help
                exit 0
                ;;
            "-h" )
                print_help
                exit 0
                ;;
            "--report" )
                generate_report
                exit 0 
                ;;
            "--config" )
                shift
                configFile=$1
                ;;
            *)
                print_info "Traced Command: $*"
                collect_trace $*
                generate_report
                exit 0
                ;;
        esac
        shift
    done
}

##### Main() ##### 
main $*
