#!/bin/sh
function print_help()
{
    echo "$0 [OPTIONS, ...] command [command args...]"
    echo "    OPTIONS: None"
}

function encapsulate()
{
    whitespace="[[:space:]]"
    for i in "$@"
    do
        if [[ $i =~ $whitespace ]]
        then
            i=\"$i\"
        fi
        # echo "$i"
        args+="$i "
    done

    echo ${args}
}

options=""
while [[ 1 ]]; do
    case "$1" in
        "--help" )
            print_help
            exit 0
            ;;
        "-h" )
            print_help
            exit 0
            ;;
        *)
            break
            ;;
    esac
    shift 1 # Remove the fisrt argument
done
args=$*
rm -f perf.data
#Communication Traces
tcpdump -w sofa.pcap & 
#Computation Traces
perf record -F 1000 -a ${args} && pkill tcpdump
perf script > perf.script

echo "script source = $(dirname $0)"
$(dirname $0)/fsa default.cfg
