#!/bin/sh
echo $1
echo $2
pssh -PH "$1" "sleep 1 &&  echo "/tmp/perf-"\`hostname\`".data""

pssh -PH "$1" "perf record -a -o /tmp/perf-"\`hostname\`".data sleep $2 && perf script -i /tmp/perf-"\`hostname\`".data > /tmp/perf-"\`hostname\`".script && scp /tmp/perf-"\`hostname\`".script hpc0:/tmp/sofa-dist-data/"

